/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 car.glb 
Author: Karol Miklas (https://sketchfab.com/karolmiklas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-gmc-motorhome-reimagined-low-poly-6hiH0iyDqXqtdD9wbqSbyLLhKmz
Title: FREE GMC Motorhome reimagined low poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.interior} position={[0.76, 0.244, 3.398]} rotation={[-0.136, 0.002, 0.012]} scale={1.06} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.interior} position={[0.842, 0.293, 3.476]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.interior} position={[0.752, 0.13, 2.731]} scale={[0.245, 0.288, 0.245]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.interior} scale={1.169} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.interior} position={[-0.656, 0.293, 3.476]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.interior} position={[-0.746, 0.1, 2.847]} rotation={[-Math.PI, 0.463, -Math.PI]} scale={[0.245, 0.288, 0.245]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.clay} scale={1.169} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['clay.001']} position={[0, -0.96, 3.058]} rotation={[-0.483, 0, 0]} scale={1.169} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['clay.001']} position={[0, -0.96, -1.141]} rotation={[0.247, 0, 0]} scale={1.169} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['clay.001']} position={[0, -0.96, -2.186]} rotation={[-1.205, 0, 0]} scale={1.169} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.windows} scale={1.169} />
    </group>
  )
}

useGLTF.preload('/car.glb')
