/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 demo3.glb 
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'
import goku from './goku.jpg'
export default function Model(props) {
  let logoTexture=useTexture(goku)
  
  let color="red"
  let color2="green"
  let color3="yellow"
  const { nodes, materials } = useGLTF('/demo3.glb')
  return (
    <group {...props} dispose={null}scale={[15,15,15]}>
      <group position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]}>
        <mesh geometry={nodes.polySurface1.geometry} material={materials.Sleeve_shader_L}  material-color={color}/>
        <mesh geometry={nodes.polySurface2.geometry} material={materials.Sleeve_Shader_R} material-color={color2}/>
      </group>
      <mesh geometry={nodes.T_Shirt3.geometry} material={materials.Back_Shader_1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]}  material-color={color3}>
        
      <Decal
          position={[0,0,0]}
          rotation={[0, 0, 0]}
          scale={[0.9,0.9,0.9]}
          map={logoTexture}
         
        />
        
        </mesh>
      <mesh geometry={nodes.T_Shirt6.geometry} material={materials.Front_Shader_1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
    </group>
  )
}

useGLTF.preload('/demo3.glb')
