/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 green_hoodie.glb 
Author: Style3D CG (https://sketchfab.com/Style3DMeta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-and-white-hoodie-af100701826e4bb9abc1ff1a1d24ab1e
Title: Green and white hoodie
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/green_hoodie.glb')
  return (
    <group  position={[2,1,1]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.uniform_1001} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.uniform_1001} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.uniform_1001} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.uniform_1001} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.uniform_1001} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.uniform_1001} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.uniform_1001} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.uniform_1001} />
      </group>
    </group>
  )
}

useGLTF.preload('/green_hoodie.glb')
