/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hoodie_with_hood_up.glb 
Author: chop24 (https://sketchfab.com/chop24)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hoodie-with-hood-up-237449b193714dfaa13b9a4d9d2b9a90
Title: Hoodie with hood up
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hoodie_with_hood_up.glb')
  
  return (
    <group position={[2,1,1]} {...props} dispose={null} scale={[5,5,5]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material238904.005']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material238904.005']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material238904.005']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material238904.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/hoodie_with_hood_up.glb')
