/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 polo_shirt.glb 
Author: mdsinteractive (https://sketchfab.com/mdsinteractive)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polo-white-tshirt-a0c1185e7da24a9484c1055bb27b379f
Title: Polo_white tshirt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/polo_shirt.glb')
  return (
    <group {...props} dispose={null} scale={[5,5,5]}>
      <group scale={0.025}>
        <group position={[0.033, 0, 0.061]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-0.229, -0.789, 14.583]} rotation={[0.087, 0.007, 0]}>
            <group position={[8.962, 1.93, 1.836]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.polySurface3_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[-22.398, -41.775, 3.083]} />
            </group>
            <group position={[0.151, 3.349, -0.409]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.polySurface4_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[-0.017, -36.075, 6.687]} />
            </group>
            <group position={[0.022, 1.501, 9.317]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.polySurface37_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[0.311, -60.778, 1.994]} />
            </group>
            <group position={[0.166, -1.519, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.ShirtpolySurface36_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[-0.055, -37.139, -5.677]} />
            </group>
            <group position={[-8.518, 1.93, 6.261]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.ShirtpolySurface39_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[22.001, -53.016, 3.082]} />
            </group>
            <group position={[8.829, 1.921, 6.231]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.ShirtpolySurface38_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[-22.06, -52.939, 3.06]} />
            </group>
            <group position={[-8.637, 1.924, 1.974]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.polySurface38_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[22.304, -42.126, 3.067]} />
            </group>
            <group position={[-0.585, -1.993, 9.475]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.ShirtShirtShirtpolySurface44_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[1.851, -61.18, -6.882]} />
            </group>
            <group position={[-0.555, -1.947, 9.48]} rotation={[Math.PI / 2, 0, 0]} scale={0.394}>
              <mesh geometry={nodes.ShirtShirtpolySurface50_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[1.777, -61.191, -6.764]} />
            </group>
            <mesh geometry={nodes.pCube1_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[0.146, 4.257, 12.082]} rotation={[1.96, -0.02, 0]} scale={[1.457, 0.321, 0.031]} />
            <mesh geometry={nodes.pCube2_re_work_phong1__0.geometry} material={materials.re_work_phong1} position={[0.144, 4.33, 11.859]} rotation={[Math.PI / 2, 0, 0]} scale={[0.157, 0.157, 0.082]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/polo_shirt.glb')
