/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 poncho.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/poncho.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_14.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_15.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_16.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_17.geometry} material={materials.Rib_2X2_468gsm_263076} />
      <mesh geometry={nodes.Cloth_mesh_18.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_19.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266284} />
      <mesh geometry={nodes.Cloth_mesh_20.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_21.geometry} material={materials.Trim_Full_Grain_Leather_256171} />
      <mesh geometry={nodes.Cloth_mesh_22.geometry} material={materials.Trim_Full_Grain_Leather_256171} />
      <mesh geometry={nodes.Cloth_mesh_23.geometry} material={materials.Trim_Full_Grain_Leather_256171} />
      <mesh geometry={nodes.Cloth_mesh_24.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_25.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266284} />
      <mesh geometry={nodes.Cloth_mesh_26.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_27.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_28.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266284} />
      <mesh geometry={nodes.Cloth_mesh_29.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_30.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
      <mesh geometry={nodes.Cloth_mesh_31.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266284} />
      <mesh geometry={nodes.Cloth_mesh_32.geometry} material={materials.Sherpa_Shearling_Curly_Fleece_Poly_360gsm_266277} />
    </group>
  )
}

useGLTF.preload('/poncho.glb')
