/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Roundneck.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Roundneck.glb')
  return (
    <group {...props} dispose={null} scale={[25, 25, 25]}>
      <mesh geometry={nodes.T_Shirt2.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt3.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt6.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt7.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt8.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt9.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
    </group>
  )
}

useGLTF.preload('/Roundneck.glb')
