/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 T_shirt_Demo.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/T_shirt_Demo.glb')
  let color="red"
  return (
    <group {...props} dispose={null} scale={[15,15,15]}>
      <mesh geometry={nodes.T_Shirt2.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]}  >
        </mesh>
        <mesh geometry={nodes.T_Shirt3.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
        <mesh geometry={nodes.T_Shirt6.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]}material-color={color} />
    </group>
  )
}

useGLTF.preload('/T_shirt_Demo.glb')
