/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tshirt.glb 
Author: lukedew99 (https://sketchfab.com/lukedew99)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tshirt-493ccd4e2b6a443c87ba4264fe7cadfa
Title: Tshirt
*/

import React, { useRef, useState } from 'react'
import { Box, Decal, useGLTF, useTexture } from '@react-three/drei'
import goku from './goku.jpg';


import { useControls } from "leva";


export default function Model(props) {
  const { nodes, materials } = useGLTF('/tshirt.glb')
  const [scale, setScale] = useState([0.10, 0.10, 0.10]);
  let logoTexture = useTexture(goku)
 



  useControls({
    
    scale: {
      min: 0.1,
      max: 2,
      value: 0.25,
      step: 0.01,
      onChange: (value) => {
        setScale(() => [value, value, 1.5]);
      },
    },
  });


  let decal




  if(props.position){
  decal=props.position
  
  
  }
  else{
  
     decal=[0, 0.04, 0.15]
  
  }



  return (
    <group {...props} dispose={null} scale={[0.05,0.05,0.05]}>
      <group rotation={[-Math.PI / 2, 0.01, 0]}>
        
      <mesh geometry={nodes.Object_2.geometry} material={materials.Shirt}  material-color={props.color}>
        <Decal
          position={decal} // Adjust position as needed
          rotation={[0,0,0]} // No rotation
          scale={scale} // Adjust scale as needed
          map={logoTexture} // Use the logoTexture as the decal texture
         
          
        />
          
          </mesh>
          <mesh geometry={nodes.Object_3.geometry} material={materials.Shirt} >
            
          <Decal
          position={decal} // Adjust position as needed
          rotation={[0,0,0]} // No rotation
          scale={scale} // Adjust scale as needed
          map={logoTexture} // Use the logoTexture as the decal texture
         
          
        />


            </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/tshirt.glb')
