/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vneck.glb 
*/

import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'

export default function Model(props) {


let logoTexture=null

const image=props.image

if(image){

   logoTexture = useTexture(image)

}


  const { nodes, materials } = useGLTF('/vneck.glb')

  let color='red'
const material1 = materials.lambert1.clone()
material1.color.set(color)
  return (
    <group {...props} dispose={null} scale={[15, 15, 15]}>
      <mesh geometry={nodes.T_Shirt2.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} >
      <Decal
          position={[0, 0, 0]} // Adjust position as needed
          rotation={[0, 0, 0]} // No rotation
          scale={[0.15, 0.15, 0.15]} // Adjust scale as needed
          map={logoTexture} // Use the logoTexture as the decal texture
          tintColor={0xff0000} 
          
        />
        
        </mesh>
      <mesh geometry={nodes.T_Shirt5.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt6.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt7.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt8.geometry} material={materials.lambert1} position={[0, 0.133, -0.001]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
      <mesh geometry={nodes.T_Shirt9.geometry} material={materials.lambert1} position={[0, 0.133, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.033, 0.036, 0.07]} />
    </group>
  )
}

useGLTF.preload('/vneck.glb')
