/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Praveen (https://sketchfab.com/praveen889zealous)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fashion-dress-931ced7d97bd4e0d8e2d971776011e3d
Title: Fashion Dress
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.object_0_object_0_0.geometry} material={materials.object_0} position={[0, -21.165, 0]} scale={3.017} />
        <mesh geometry={nodes.object_1_object_1_0.geometry} material={materials.object_1} position={[0, -21.165, 0]} scale={3.017} />
        <mesh geometry={nodes.object_2_object_2_0.geometry} material={materials.object_2} position={[0, -21.165, 0]} scale={3.017} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
